dist: xenial
sudo: required

language: c

addons:
  apt:
    update: true
    packages:
      - libmbedtls-dev
      - libev-dev
      - libev-libevent-dev

script:
  - ./autogen.sh && ./configure && make
